### ISSUE TITLE
Additional configuration and information required to stand up portainer instance

### ISSUE THREAD

**Issue by nathanieloon** [openeyes/Docker#3]
There's some additional information/rewording required to standup the portainer instance:

- [x] The SSL host is currently hardcoded as `abehrdigital.com` in a couple of places in the `docker-compose.yml` file
- [x] A dummy `acme.json` file is required for traefik to stand up correctly
- [x] There's a deprecated traefik acme parameter (I don't think this causes any issues though)
- [x] Improve the README where possible

**Comment by nathanieloon** [comment]
@biskyt I've got a branch with all of these changes but I don't have access to push to the repo so I can't create a PR for it.

**Comment by biskyt** [comment]
@nathanieloon - if you create a PR from your repo then I can check and merge
